// Generated by Figma Token Sync.
// Source file: rdesign灵犀2.0
// Generated at: 2026-04-25T03:04:00.290Z

import 'rd_default_colors.dart';
import 'rd_sl_colors.dart';
import 'rd_sl_orange_colors.dart';
import 'rd_mrj_colors.dart';

export 'rd_default_colors.dart';
export 'rd_sl_colors.dart';
export 'rd_sl_orange_colors.dart';
export 'rd_mrj_colors.dart';

class RDThemeTokenSpec {
  const RDThemeTokenSpec({
    required this.id,
    required this.darkId,
    required this.lightJson,
    required this.darkJson,
  });

  final String id;
  final String darkId;
  final String lightJson;
  final String darkJson;
}

const List<RDThemeTokenSpec> rdThemeTokenSpecs = [
  RDThemeTokenSpec(
    id: 'default',
    darkId: 'defaultDark',
    lightJson: rdDefaultLightJson,
    darkJson: rdDefaultDarkJson,
  ),
  RDThemeTokenSpec(
    id: 'sl',
    darkId: 'slDark',
    lightJson: rdSlLightJson,
    darkJson: rdSlDarkJson,
  ),
  RDThemeTokenSpec(
    id: 'sl_orange',
    darkId: 'sl_orangeDark',
    lightJson: rdSlOrangeLightJson,
    darkJson: rdSlOrangeDarkJson,
  ),
  RDThemeTokenSpec(
    id: 'mrj',
    darkId: 'mrjDark',
    lightJson: rdMrjLightJson,
    darkJson: rdMrjDarkJson,
  ),
];
